### ISSUE TITLE
自动生成的前端报错：[vite] Internal server error: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by 404name** [uncarbon97/helio-generator#4]
暂时遇到的问题：
1. 前端页面比如我生成了Test/index 访问首页对应的地方会显示[vite] Internal server error: EISDIR: illegal operation on a directory, read
- 但我把Test/index的内容改成vben/about/index又没问题0.0，我就不清楚是怎么回事了

2. 后端生成的代码，测试代码有一个全局生成的XxxService xxxService，测试函数内应该调用小写的xxxService，但我生成的情况是测试函数内是大写的，需要手动改成对象

**Comment by uncarbon97** [comment]
1. 因为缺少代码和目录结构，我不是很确定是什么原因。只是有一个大胆的猜想：  
    现在的后台管理权限控制一般是根据菜单定义的路由，动态加载 .vue 文件到 router 中。
    尝试在后台管理-菜单管理中，新增一项菜单（ .vue 文件存放位置 和 路由路径 参考原有项目），利用超管账号特权， .vue 页面 也许会自动 load 到 router 中，可能就能访问到了。
2. 第二点的确是我的失误，需要将 `UnitTest.java.vm` 的 `${className}Service.` 替换为 `${classname}Service.` 即可
